### ISSUE TITLE
Error: 'eval_select' is not an exported object from 'namespace:tidyselect'

### ISSUE THREAD

**Issue by valrin1** [r-lib/tidyselect#219]
Does anyone know how I can fix this?

**Comment by lionel-** [comment]
Reinstalling tidyselect should fix it. In general when you get this sort of errors, update your packages (all of them is best).

**Comment by valrin1** [comment]
Hi Lionel, thanks so much for getting to my question so quickly. However, when I restart the tidyselect package I still get the error. I should note that I do not have the most up-to-date version of R since my computer's memory and storage won't allow for it. Is there a similar function in an older package that I can use to substitute the select () function?

**Comment by lionel-** [comment]
Did you mean "reinstall" instead of "restart"?

Sorry you either need both old dplyr and old tidyselect installed, or new dplyr and new (or old) tidyselect. It looks like you are in a situation with old dplyr and new tidyselect, which cannot work. I would keep trying to update tidyselect.
